services:
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,LISTENER:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'CONTROLLER://kafka:29093,LISTENER://kafka:29092,EXTERNAL://0.0.0.0:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER'
    # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
    # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: 'venpz0h7QE2i8DFV5NZMvQ'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:latest
    restart: always
    hostname: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    command: ['postgres', '-c', 'wal_level=logical']
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  debezium:
    image: debezium/connect:latest
    restart: always
    hostname: debezium
    container_name: debezium
    ports:
      - '8083:8083'
    depends_on:
      - kafka
      - postgres
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_configs
      OFFSET_STORAGE_TOPIC: debezium_offsets
      STATUS_STORAGE_TOPIC: debezium_statuses
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: false
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: false
      CONNECT_TOPIC_CREATION_ENABLE: true
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '--silent',
          '--fail',
          '-X',
          'GET',
          'http://localhost:8083/connectors',
        ]
      start_period: 10s
      interval: 10s
      timeout: 5s 
      retries: 3

  debezium-init:
    image: curlimages/curl:latest
    restart: no
    container_name: debezium-init 
    depends_on:
      debezium:
        condition: service_healthy
    entrypoint: [
                  'curl',
                  '-X','POST',
                  '--location','http://debezium:8083/connectors',
                  '-H','Content-Type: application/json',
                  '-H','Accept: application/json','-d',
                  '{
                    "config":{
                      "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
                      "tasks.max": "1",
                      "topic.prefix": "orders",
                      "database.hostname": "postgres",
                      "database.port": "5432",
                      "database.user": "postgres",
                      "database.password": "postgres",
                      "database.dbname": "orders_db",
                      "database.server.name": "postgres",
                      "database.history.kafka.bootstrap.servers": "kafka:9092",
                      "plugin.name": "pgoutput",
                      "topic.creation.default.replication.factor": 1,
                      "topic.creation.enable": "true",
                      "topic.creation.default.partitions": 1
                    },
                    "name": "orders-connector"
                  }'
                ]


  debezium-ui:
    image: debezium/debezium-ui:latest
    restart: always
    hostname: debezium-ui
    container_name: debezium-ui
    ports:
      - '8080:8080'
    depends_on:
      - debezium
    environment:
      KAFKA_CONNECT_URIS: http://debezium:8083

  mock-data:
    build:
      context: ./mock_data
      dockerfile: Dockerfile
    container_name: mock-data
    restart: no
    depends_on:
      postgres:
        condition: service_healthy

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - '8123:8123'
      - '9000:9000'
    environment:
      CLICKHOUSE_DB: orders_analytics
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
